index:
    path: /
    controller: App\Controller\LocatorController::index
list_partners:
    path: /partners
    controller: App\Controller\LocatorController::listPartners
list_categories:
    path: /categories
    controller: App\Controller\LocatorController::listCategories
list_countries:
    path: /countries
    controller: App\Controller\LocatorController::listCountries
